{
  "info": {
    "description": "Institution Service",
    "title": "UCP Institution Service",
    "version": "0.1.0"
  },
  "openapi": "3.0.0",
  "components": {
    "securitySchemes": {
      "bearerAuth": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      }
    }
  },
  "servers": [
    {
      "description": "Institution Service",
      "url": "http://localhost:8088"
    }
  ],
  "paths": {
    "/aggregators": {
      "get": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "description": "Get Aggregators",
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "aggregators": [
                      {
                        "id": 2,
                        "name": "finicity",
                        "displayName": "Finicity",
                        "logo": "https://universalconnectproject.org/images/ucp-logo-icon.svg",
                        "createdAt": "2024-10-09T17:01:07.593Z",
                        "updatedAt": "2024-10-09T17:01:07.593Z"
                      },
                      {
                        "id": 1,
                        "name": "sophtron",
                        "displayName": "Sophtron",
                        "logo": "https://sophtron.com/Images/logo.png",
                        "createdAt": "2024-10-09T17:01:07.587Z",
                        "updatedAt": "2024-10-09T17:01:07.587Z"
                      },
                      {
                        "id": 98,
                        "name": "mx",
                        "displayName": "MX",
                        "logo": "https://content.moneydesktop.com/storage/MD_Assets/Ipad%20Logos/100x100/INS-3aeb38da-26e4-3818-e0fa-673315ab7754_100x100.png",
                        "createdAt": "2024-10-09T17:01:07.537Z",
                        "updatedAt": "2024-10-09T17:01:07.537Z"
                      }
                    ]
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          }
        }
      }
    },
    "/institutions/cacheList": {
      "get": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "description": "Get the entire institution list formatted to save in the UCW-app",
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": [
                    {
                      "id": "b2c01271-10e3-4f24-9236-44719e41fb40",
                      "name": "FinBank Profiles - A",
                      "keywords": ["finbank", "finicity"],
                      "logo": "https://prod-carpintero-branding.s3.us-west-2.amazonaws.com/102105/icon.svg",
                      "url": "http://www.finbank.com",
                      "is_test_bank": true,
                      "routing_numbers": [],
                      "finicity": {
                        "id": "102105",
                        "supports_oauth": false,
                        "supports_identification": true,
                        "supports_verification": true,
                        "supports_aggregation": true,
                        "supports_history": false,
                        "supportsBalance": false,
                        "supportsRewards": false
                      }
                    },
                    {
                      "id": "a44e81b6-127f-46fb-be3f-8898354c95f1",
                      "name": "MX Bank (Oauth)",
                      "keywords": ["Gringotts", "MX Bank", "oauth"],
                      "logo": "https://s3.amazonaws.com/MD_Assets/Ipad%20Logos/100x100/INS-3aeb38da-26e4-3818-e0fa-673315ab7754_100x100.png",
                      "url": "https://mx.com",
                      "is_test_bank": true,
                      "routing_numbers": [],
                      "mx": {
                        "id": "mx_bank_oauth",
                        "supports_oauth": true,
                        "supports_identification": true,
                        "supports_verification": true,
                        "supports_aggregation": false,
                        "supports_history": false,
                        "supportsBalance": false,
                        "supportsRewards": false
                      }
                    },
                    {
                      "id": "ee0afbc5-47ab-4e6e-aa32-fea3a91fa606",
                      "name": "Alabama Credit Union",
                      "keywords": ["ACU", "Alabama CU", "Alabama Credit Union"],
                      "logo": "https://content.moneydesktop.com/storage/MD_Assets/Ipad%20Logos/100x100/INS-c4d51160-465e-1d78-4a50-fd6836684c3a_100x100.png",
                      "url": "https://www.alabamacu.com/",
                      "is_test_bank": false,
                      "routing_numbers": ["262277419"],
                      "mx": {
                        "id": "alabamacreditunion",
                        "supports_oauth": false,
                        "supports_identification": true,
                        "supports_verification": true,
                        "supports_aggregation": true,
                        "supports_history": true,
                        "supportsBalance": true,
                        "supportsRewards": true
                      },
                      "sophtron": {
                        "id": "4D1C263B-D291-4DF7-9F22-79E445E59526",
                        "supports_oauth": false,
                        "supports_identification": true,
                        "supports_verification": true,
                        "supports_aggregation": false,
                        "supports_history": false,
                        "supportsBalance": false,
                        "supportsRewards": false
                      },
                      "finicity": {
                        "id": "5411",
                        "supports_oauth": false,
                        "supports_identification": true,
                        "supports_verification": false,
                        "supports_aggregation": true,
                        "supports_history": false,
                        "supportsBalance": false,
                        "supportsRewards": false
                      }
                    }
                  ]
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          }
        },
        "summary": "Institution Cache List with widget authorization"
      }
    },
    "/institutions/cacheList/download": {
      "get": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "description": "Get the entire institution list formatted to save in the UCW-app",
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": [
                    {
                      "id": "b2c01271-10e3-4f24-9236-44719e41fb40",
                      "name": "FinBank Profiles - A",
                      "keywords": ["finbank", "finicity"],
                      "logo": "https://prod-carpintero-branding.s3.us-west-2.amazonaws.com/102105/icon.svg",
                      "url": "http://www.finbank.com",
                      "is_test_bank": true,
                      "routing_numbers": [],
                      "finicity": {
                        "id": "102105",
                        "supports_oauth": false,
                        "supports_identification": true,
                        "supports_verification": true,
                        "supports_aggregation": true,
                        "supports_history": false,
                        "supportsBalance": false,
                        "supportsRewards": false
                      }
                    },
                    {
                      "id": "a44e81b6-127f-46fb-be3f-8898354c95f1",
                      "name": "MX Bank (Oauth)",
                      "keywords": ["Gringotts", "MX Bank", "oauth"],
                      "logo": "https://s3.amazonaws.com/MD_Assets/Ipad%20Logos/100x100/INS-3aeb38da-26e4-3818-e0fa-673315ab7754_100x100.png",
                      "url": "https://mx.com",
                      "is_test_bank": true,
                      "routing_numbers": [],
                      "mx": {
                        "id": "mx_bank_oauth",
                        "supports_oauth": true,
                        "supports_identification": true,
                        "supports_verification": true,
                        "supports_aggregation": false,
                        "supports_history": false,
                        "supportsBalance": false,
                        "supportsRewards": false
                      }
                    },
                    {
                      "id": "ee0afbc5-47ab-4e6e-aa32-fea3a91fa606",
                      "name": "Alabama Credit Union",
                      "keywords": ["ACU", "Alabama CU", "Alabama Credit Union"],
                      "logo": "https://content.moneydesktop.com/storage/MD_Assets/Ipad%20Logos/100x100/INS-c4d51160-465e-1d78-4a50-fd6836684c3a_100x100.png",
                      "url": "https://www.alabamacu.com/",
                      "is_test_bank": false,
                      "routing_numbers": ["262277419"],
                      "mx": {
                        "id": "alabamacreditunion",
                        "supports_oauth": false,
                        "supports_identification": true,
                        "supports_verification": true,
                        "supports_aggregation": true,
                        "supports_history": true,
                        "supportsBalance": true,
                        "supportsRewards": true
                      },
                      "sophtron": {
                        "id": "4D1C263B-D291-4DF7-9F22-79E445E59526",
                        "supports_oauth": false,
                        "supports_identification": true,
                        "supports_verification": true,
                        "supports_aggregation": false,
                        "supports_history": false,
                        "supportsBalance": false,
                        "supportsRewards": false
                      },
                      "finicity": {
                        "id": "5411",
                        "supports_oauth": false,
                        "supports_identification": true,
                        "supports_verification": false,
                        "supports_aggregation": true,
                        "supports_history": false,
                        "supportsBalance": false,
                        "supportsRewards": false
                      }
                    }
                  ]
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          }
        },
        "summary": "Institution Cache List with permissions for regular UI users"
      }
    },
    "/institutions/{id}": {
      "delete": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "description": "Delete an Institution",
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "schema": {
              "type": "string",
              "description": "UUID v4"
            },
            "required": true,
            "description": "UCP ID of the Institution to delete"
          }
        ],
        "responses": {
          "204": {
            "description": "Deleted"
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "error": "Aggregator cannot edit an institution used by other aggregators"
                  }
                }
              }
            }
          }
        }
      },
      "put": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "description": "Update an Institution",
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "schema": {
              "type": "string",
              "description": "UUID v4"
            },
            "required": true,
            "description": "UCP ID of the Institution to update"
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string"
                  },
                  "keywords": {
                    "type": "array",
                    "items": {
                      "type": "string"
                    }
                  },
                  "logo": {
                    "type": "string"
                  },
                  "url": {
                    "type": "string"
                  },
                  "is_test_bank": {
                    "type": "boolean"
                  },
                  "routing_numbers": {
                    "type": "array",
                    "items": {
                      "type": "string"
                    }
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Updated",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "message": "Institution updated successfully",
                    "institution": {
                      "id": "UCP-024b97a3cd4d4df",
                      "name": "FinBank Profiles - A",
                      "keywords": ["finbank", "finicity"],
                      "logo": "https://prod-carpintero-branding.s3.us-west-2.amazonaws.com/102105/icon.svg",
                      "url": "http://www.finbank.com",
                      "is_test_bank": true,
                      "routing_numbers": ["123456789"],
                      "createdAt": "2024-09-10T16:07:46.038Z",
                      "updatedAt": "2024-09-11T17:22:35.653Z"
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "error": "\"logo\" must be a valid uri with a scheme matching the http|https pattern"
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "error": "Aggregator cannot edit an institution used by other aggregators"
                  }
                }
              }
            }
          }
        }
      },
      "get": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "description": "Gets an Institution",
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "schema": {
              "type": "string",
              "description": "UUID v4"
            },
            "required": true,
            "description": "UCP ID of the Institution being requested"
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "institution": {
                      "id": "ee6d71dc-e693-4fc3-a775-53c378bc5066",
                      "name": "Alabama Credit Union",
                      "keywords": ["ACU", "Alabama CU", "Alabama Credit Union"],
                      "logo": "https://content.moneydesktop.com/storage/MD_Assets/Ipad%20Logos/100x100/INS-c4d51160-465e-1d78-4a50-fd6836684c3a_100x100.png",
                      "url": "https://www.alabamacu.com/",
                      "is_test_bank": false,
                      "routing_numbers": ["262277419"],
                      "createdAt": "2024-09-23T15:33:58.485Z",
                      "updatedAt": "2024-09-23T15:33:58.485Z",
                      "aggregatorIntegrations": [
                        {
                          "id": 3,
                          "aggregator_institution_id": "alabamacreditunion",
                          "supports_oauth": false,
                          "supports_identification": true,
                          "supports_verification": true,
                          "supports_aggregation": true,
                          "supports_history": true,
                          "supportsBalance": true,
                          "supportsRewards": true,
                          "createdAt": "2024-09-23T15:33:58.173Z",
                          "updatedAt": "2024-09-23T15:33:58.173Z",
                          "isActive": true,
                          "aggregator": {
                            "name": "mx",
                            "id": 1,
                            "displayName": null,
                            "logo": null
                          }
                        },
                        {
                          "id": 4,
                          "aggregator_institution_id": "4D1C263B-D291-4DF7-9F22-79E445E59526",
                          "supports_oauth": false,
                          "supports_identification": true,
                          "supports_verification": true,
                          "supports_aggregation": true,
                          "supports_history": false,
                          "supportsBalance": false,
                          "supportsRewards": false,
                          "createdAt": "2024-09-23T15:33:58.173Z",
                          "updatedAt": "2024-09-23T15:33:58.173Z",
                          "isActive": true,
                          "aggregator": {
                            "name": "sophtron",
                            "id": 2,
                            "displayName": null,
                            "logo": null
                          }
                        },
                        {
                          "id": 5,
                          "aggregator_institution_id": "5411",
                          "supports_oauth": false,
                          "supports_identification": true,
                          "supports_verification": false,
                          "supports_aggregation": true,
                          "supports_history": false,
                          "supportsBalance": false,
                          "supportsRewards": false,
                          "createdAt": "2024-09-23T15:33:58.173Z",
                          "updatedAt": "2024-09-23T15:33:58.173Z",
                          "isActive": false,
                          "aggregator": {
                            "name": "finicity",
                            "id": 3,
                            "displayName": null,
                            "logo": null
                          }
                        }
                      ]
                    },
                    "permissions": {
                      "aggregatorIntegrationPermissionsMap": {
                        "3": {
                          "canDelete": true,
                          "canEdit": true
                        },
                        "4": {
                          "canDelete": false,
                          "canEdit": false
                        },
                        "5": {
                          "canDelete": false,
                          "canEdit": false
                        }
                      },
                      "canDeleteInstitution": false,
                      "canEditInstitution": false,
                      "aggregatorsThatCanBeAdded": [
                        {
                          "displayName": "MX",
                          "id": 10
                        }
                      ],
                      "hasAccessToAllAggregators": true
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "error": "Institution not found"
                  }
                }
              }
            }
          }
        },
        "summary": "Institution Detail"
      }
    },
    "/permissions": {
      "get": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "description": "Get institution permissions",
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "canCreateInstitution": true
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          }
        }
      }
    },
    "/institutions": {
      "get": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "description": "Get the paginated list of Institutions",
        "parameters": [
          {
            "in": "query",
            "name": "page",
            "schema": {
              "type": "integer",
              "default": 1
            },
            "required": false,
            "example": 30,
            "description": "Page to be returned in the paginated response."
          },
          {
            "in": "query",
            "name": "pageSize",
            "schema": {
              "type": "integer",
              "default": 10
            },
            "required": false,
            "example": 3,
            "description": "The number of institutions to be returned in the paginated response."
          },
          {
            "in": "query",
            "name": "search",
            "schema": {
              "type": "string",
              "example": "American"
            },
            "required": false,
            "example": "American",
            "description": "Search term for Institutions query"
          },
          {
            "in": "query",
            "name": "includeInactiveIntegrations",
            "schema": {
              "type": "boolean",
              "enum": [true],
              "example": true
            },
            "required": false,
            "example": true,
            "description": "When using aggregator integration filters include institutions that have inactive integrations that match the filters"
          },
          {
            "in": "query",
            "name": "supportsOauth",
            "schema": {
              "type": "boolean",
              "enum": [true],
              "example": true
            },
            "required": false,
            "example": true,
            "description": "Only show Institutions that support Oauth"
          },
          {
            "in": "query",
            "name": "supportsAggregation",
            "schema": {
              "type": "boolean",
              "enum": [true],
              "example": true
            },
            "required": false,
            "example": true,
            "description": "Only show Institutions that support aggregation"
          },
          {
            "in": "query",
            "name": "supportsVerification",
            "schema": {
              "type": "boolean",
              "enum": [true],
              "example": true
            },
            "required": false,
            "example": true,
            "description": "Only show Institutions that support verification"
          },
          {
            "in": "query",
            "name": "supportsIdentification",
            "schema": {
              "type": "boolean",
              "enum": [true],
              "example": true
            },
            "required": false,
            "example": true,
            "description": "Only show Institutions that support identification"
          },
          {
            "in": "query",
            "name": "supportsHistory",
            "schema": {
              "type": "boolean",
              "enum": [true],
              "example": true
            },
            "required": false,
            "example": true,
            "description": "Only show Institutions that support extended transaction history"
          },
          {
            "in": "query",
            "name": "aggregatorName",
            "schema": {
              "type": "array",
              "items": {
                "type": "string"
              }
            },
            "required": false,
            "style": "form",
            "explode": true,
            "example": ["mx", "sophtron"],
            "description": "Institutions must include an integration by at least one of these aggregators"
          },
          {
            "in": "query",
            "name": "sortBy",
            "schema": {
              "type": "string"
            },
            "required": false,
            "style": "form",
            "explode": true,
            "example": "createdAt:DESC",
            "description": "Field to sort by. Use the field name followed by an optional colon and the sort direction: ASC (default) or DESC."
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": [
                    {
                      "currentPage": 30,
                      "pageSize": 3,
                      "totalRecords": 29489,
                      "totalPages": 9830,
                      "institutions": [
                        {
                          "id": "94b05c68-bab7-4694-9695-5934d8adf722",
                          "name": "Preferred Trust ",
                          "keywords": [],
                          "logo": null,
                          "url": "https://preferredtrustcompany.com/",
                          "is_test_bank": false,
                          "routing_numbers": [],
                          "createdAt": "2024-09-23T15:33:58.664Z",
                          "updatedAt": "2024-09-23T15:33:58.664Z",
                          "aggregatorIntegrations": [
                            {
                              "aggregator_institution_id": "5a74733d-aa8f-471a-b454-ca5bfda01902",
                              "supports_oauth": false,
                              "supports_identification": false,
                              "supports_verification": false,
                              "supports_aggregation": true,
                              "supports_history": false,
                              "supportsBalance": false,
                              "supportsRewards": false,
                              "isActive": true,
                              "aggregator": {
                                "name": "mx",
                                "id": 1,
                                "displayName": null,
                                "logo": null
                              }
                            },
                            {
                              "aggregator_institution_id": "2bbdf338-7fcc-4655-9c4d-5ccaffb60b2a",
                              "supports_oauth": false,
                              "supports_identification": false,
                              "supports_verification": false,
                              "supports_aggregation": true,
                              "supports_history": false,
                              "supportsBalance": false,
                              "supportsRewards": false,
                              "isActive": true,
                              "aggregator": {
                                "name": "sophtron",
                                "id": 2,
                                "displayName": null,
                                "logo": null
                              }
                            }
                          ]
                        },
                        {
                          "id": "5670bd8e-13c1-411f-bc88-34abf02ba6e4",
                          "name": "Greater State Bank (TX)",
                          "keywords": [],
                          "logo": "https://content.moneydesktop.com/storage/MD_Assets/Ipad%20Logos/100x100/default_100x100.png",
                          "url": "https://greaterstate.bank/",
                          "is_test_bank": false,
                          "routing_numbers": [],
                          "createdAt": "2024-09-23T15:33:58.664Z",
                          "updatedAt": "2024-09-23T15:33:58.664Z",
                          "aggregatorIntegrations": [
                            {
                              "aggregator_institution_id": "a9fb59b3-b9c2-4cd4-a3fc-9ca9c7eaa6cc",
                              "supports_oauth": false,
                              "supports_identification": false,
                              "supports_verification": false,
                              "supports_aggregation": true,
                              "supports_history": false,
                              "supportsBalance": false,
                              "supportsRewards": false,
                              "isActive": true,
                              "aggregator": {
                                "name": "mx",
                                "id": 1,
                                "displayName": null,
                                "logo": null
                              }
                            },
                            {
                              "aggregator_institution_id": "171045",
                              "supports_oauth": false,
                              "supports_identification": false,
                              "supports_verification": false,
                              "supports_aggregation": true,
                              "supports_history": false,
                              "supportsBalance": false,
                              "supportsRewards": false,
                              "isActive": false,
                              "aggregator": {
                                "name": "finicity",
                                "id": 3,
                                "displayName": null,
                                "logo": null
                              }
                            }
                          ]
                        },
                        {
                          "id": "e8d0a555-fc75-4e5a-9453-cad84bc0c8a4",
                          "name": "Andrews Federal Credit Union DMI ",
                          "keywords": [],
                          "logo": null,
                          "url": "https://andrewsfcu.mtgsvc.com/Account/UserLogin?conn=Q67%7B52609b13-69a0-4acd-8e5a-c3bc366bb7bd%7D",
                          "is_test_bank": false,
                          "routing_numbers": [],
                          "createdAt": "2024-09-23T15:33:58.664Z",
                          "updatedAt": "2024-09-23T15:33:58.664Z",
                          "aggregatorIntegrations": [
                            {
                              "aggregator_institution_id": "e85f0f46-1bcd-4b5f-b1a2-cb14699e9cbd",
                              "supports_oauth": false,
                              "supports_identification": false,
                              "supports_verification": false,
                              "supports_aggregation": true,
                              "supports_history": false,
                              "supportsBalance": false,
                              "supportsRewards": false,
                              "isActive": true,
                              "aggregator": {
                                "name": "mx",
                                "id": 1,
                                "displayName": null,
                                "logo": null
                              }
                            },
                            {
                              "aggregator_institution_id": "32ead61c-ad84-4a4b-8bae-66f3c0bf6ba6",
                              "supports_oauth": false,
                              "supports_identification": false,
                              "supports_verification": false,
                              "supports_aggregation": true,
                              "supports_history": false,
                              "supportsBalance": false,
                              "supportsRewards": false,
                              "isActive": true,
                              "aggregator": {
                                "name": "sophtron",
                                "id": 2,
                                "displayName": null,
                                "logo": null
                              }
                            }
                          ]
                        }
                      ]
                    }
                  ]
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          }
        },
        "summary": "Institution List"
      },
      "post": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "description": "Create an Institution",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string"
                  },
                  "keywords": {
                    "type": "array",
                    "items": {
                      "type": "string"
                    }
                  },
                  "logo": {
                    "type": "string"
                  },
                  "url": {
                    "type": "string"
                  },
                  "is_test_bank": {
                    "type": "boolean"
                  },
                  "routing_numbers": {
                    "type": "array",
                    "items": {
                      "type": "string"
                    }
                  }
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Created",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "institution": {
                      "id": "UCP-024b97a3cd4d4df",
                      "name": "FinBank Profiles - A",
                      "keywords": ["finbank", "finicity"],
                      "logo": "https://prod-carpintero-branding.s3.us-west-2.amazonaws.com/102105/icon.svg",
                      "url": "http://www.finbank.com",
                      "is_test_bank": true,
                      "routing_numbers": ["123456789"],
                      "createdAt": "2024-09-10T16:07:46.038Z",
                      "updatedAt": "2024-09-11T17:22:35.653Z"
                    },
                    "message": "Institution successfully created"
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "error": "\"logo\" must be a valid uri with a scheme matching the http|https pattern"
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          }
        }
      }
    },
    "/aggregatorIntegrations/{id}": {
      "delete": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "description": "Delete an aggregatorIntegration",
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "schema": {
              "type": "number"
            },
            "required": true,
            "description": "ID of the aggregatorIntegration to delete"
          }
        ],
        "responses": {
          "204": {
            "description": "Success"
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "error": "An Aggregator cannot edit an aggregatorIntegration belonging to another aggregator"
                  }
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "error": "AggregatorIntegration not found"
                  }
                }
              }
            }
          }
        }
      },
      "put": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "description": "Update an aggregatorIntegration",
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "schema": {
              "type": "number"
            },
            "required": true,
            "description": "ID of the aggregatorIntegration to update"
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "aggregator_institution_id": {
                    "type": "string",
                    "example": "test_bank_1"
                  },
                  "isActive": {
                    "type": "boolean",
                    "example": false
                  },
                  "supports_oauth": {
                    "type": "boolean"
                  },
                  "supports_identification": {
                    "type": "boolean"
                  },
                  "supports_verification": {
                    "type": "boolean"
                  },
                  "supports_aggregation": {
                    "type": "boolean"
                  },
                  "supports_history": {
                    "type": "boolean"
                  },
                  "supportsBalance": {
                    "type": "boolean"
                  },
                  "supportsRewards": {
                    "type": "boolean"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Updated",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "message": "AggregatorIntegration updated successfully",
                    "aggregatorIntegration": {
                      "id": 29478,
                      "isActive": false,
                      "aggregator_institution_id": "mx",
                      "aggregatorId": 4,
                      "supports_oauth": true,
                      "supports_identification": false,
                      "supports_verification": false,
                      "supports_aggregation": false,
                      "supports_history": false,
                      "supportsBalance": false,
                      "supportsRewards": false,
                      "createdAt": "2024-09-23T15:33:58.173Z",
                      "updatedAt": "2024-10-01T17:20:34.740Z",
                      "institution_id": "7a909e62-98b6-4a34-8725-b2a6a63e830a"
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "error": "\"institution_id\" is not allowed"
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "error": "An Aggregator cannot edit an aggregatorIntegration belonging to another aggregator"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/aggregatorIntegrations": {
      "post": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "description": "Create an aggregatorIntegration",
        "parameters": [],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "institution_id": {
                    "type": "string",
                    "example": "2deb6fca-557e-4d45-b2f8-354351675ad4",
                    "description": "uuid of the associated institution"
                  },
                  "aggregatorId": {
                    "type": "number",
                    "example": 2,
                    "description": "An aggregator only has permission to create aggregatorIntegrations for their aggregator"
                  },
                  "aggregator_institution_id": {
                    "type": "string",
                    "example": "test_bank_1"
                  },
                  "isActive": {
                    "type": "boolean",
                    "example": false
                  },
                  "supports_oauth": {
                    "type": "boolean"
                  },
                  "supports_identification": {
                    "type": "boolean"
                  },
                  "supports_verification": {
                    "type": "boolean"
                  },
                  "supports_aggregation": {
                    "type": "boolean"
                  },
                  "supports_history": {
                    "type": "boolean"
                  },
                  "supportsBalance": {
                    "type": "boolean"
                  },
                  "supportsRewards": {
                    "type": "boolean"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Created",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "message": "AggregatorIntegration created successfully",
                    "aggregatorIntegration": {
                      "id": 29478,
                      "isActive": false,
                      "aggregator_institution_id": "mx",
                      "aggregatorId": 4,
                      "supports_oauth": true,
                      "supports_identification": false,
                      "supports_verification": false,
                      "supports_aggregation": false,
                      "supports_history": false,
                      "supportsBalance": false,
                      "supportsRewards": false,
                      "createdAt": "2024-09-23T15:33:58.173Z",
                      "updatedAt": "2024-10-01T17:20:34.740Z",
                      "institution_id": "7a909e62-98b6-4a34-8725-b2a6a63e830a"
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "error": "\"aggregatorId\" must be a number"
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "error": "An Aggregator cannot create an aggregatorIntegration belonging to another aggregator"
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
