{
  "info": {
    "description": "Performance Service",
    "title": "UCP Performance Service",
    "version": "1.0.0"
  },
  "openapi": "3.0.0",
  "components": {
    "securitySchemes": {
      "bearerAuth": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      }
    }
  },
  "servers": [
    {
      "description": "Performance Service Dev",
      "url": "http://localhost:8090"
    }
  ],
  "paths": {
    "/metrics/allPerformanceData": {
      "get": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "description": "All performance data for the last 30 days",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Created",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "Wells Fargo": {
                      "aggregate": {
                        "successRate": {
                          "mx": 100,
                          "sophtron": 50,
                          "finicity": 100
                        },
                        "jobDuration": {
                          "mx": 40.06266666666666666,
                          "sophtron": 114.067,
                          "testAggregatorId2": 56.374
                        }
                      },
                      "verification": {
                        "successRate": {
                          "mx": 50
                        },
                        "jobDuration": {}
                      }
                    },
                    "Chase": {
                      "aggregate": {
                        "successRate": {
                          "mx": 66.67
                        },
                        "jobDuration": {
                          "mx": 30.5325
                        }
                      }
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          }
        }
      }
    },
    "/events/{connectionId}/connectionStart": {
      "post": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "description": "Begin tracking the bank connection process",
        "parameters": [
          {
            "in": "path",
            "name": "connectionId",
            "schema": {
              "type": "string"
            },
            "required": true,
            "description": "Connection ID from assigned aggregator"
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "jobTypes": {
                    "type": "array",
                    "items": {
                      "type": "string",
                      "enum": [
                        "account_verification",
                        "identity_verification",
                        "transactions",
                        "transaction_history"
                      ]
                    }
                  },
                  "institutionId": {
                    "type": "string"
                  },
                  "aggregatorId": {
                    "type": "string"
                  },
                  "ClientId": {
                    "type": "string"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Created",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "message": "Connection Tracking started",
                    "event": {
                      "connectionId": "MBR-123-455-123",
                      "institutionId": "13213-12312-123",
                      "aggregatorId": "mx",
                      "clientId": "54321",
                      "jobTypes": ["transactions"],
                      "startedAt": "2024-09-10T16:07:46.038Z"
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "error": "\"institutionId\" is required"
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          }
        }
      }
    },
    "/events/{connectionId}/connectionPause": {
      "put": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "description": "Pause the duration tracking on a connection",
        "parameters": [
          {
            "in": "path",
            "name": "connectionId",
            "schema": {
              "type": "string"
            },
            "required": true,
            "description": "Connection ID from assigned aggregator"
          }
        ],
        "responses": {
          "200": {
            "description": "Updated",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "message": "Duration tracking paused",
                    "event": {
                      "connectionId": "MBR-123-455-123",
                      "institutionId": "13213-12312-123",
                      "aggregatorId": "mx",
                      "clientId": "54321",
                      "jobTypes": ["transactions"],
                      "userInteractionTime": 0,
                      "pausedAt": "2024-09-10T16:07:51.038Z",
                      "startedAt": "2024-09-10T16:07:46.038Z",
                      "successAt": null
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "error": "\"id\" was not found"
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          }
        }
      }
    },
    "/events/{connectionId}/connectionResume": {
      "put": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "description": "Resume the duration tracking on a connection",
        "parameters": [
          {
            "in": "path",
            "name": "connectionId",
            "schema": {
              "type": "string"
            },
            "required": true,
            "description": "Connection ID from assigned aggregator"
          }
        ],
        "responses": {
          "200": {
            "description": "Updated",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "message": "Duration tracking resumed",
                    "event": {
                      "connectionId": "MBR-123-455-123",
                      "institutionId": "13213-12312-123",
                      "aggregatorId": "mx",
                      "clientId": "54321",
                      "jobTypes": ["transactions"],
                      "userInteractionTime": 140,
                      "pausedAt": "2024-09-10T16:07:51.038Z",
                      "startedAt": "2024-09-10T16:07:46.038Z",
                      "successAt": null
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "error": "\"id\" was not found"
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          }
        }
      }
    },
    "/events/{connectionId}/connectionSuccess": {
      "put": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "description": "Record the moment a connection was successful",
        "parameters": [
          {
            "in": "path",
            "name": "connectionId",
            "schema": {
              "type": "string"
            },
            "required": true,
            "description": "Connection ID from assigned aggregator"
          }
        ],
        "responses": {
          "200": {
            "description": "Updated",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "message": "Successful connection recorded",
                    "event": {
                      "connectionId": "MBR-123-455-123",
                      "institutionId": "13213-12312-123",
                      "aggregatorId": "mx",
                      "clientId": "54321",
                      "jobTypes": ["transactions"],
                      "userInteractionTime": 140,
                      "pausedAt": null,
                      "startedAt": "2024-09-10T16:07:46.038Z",
                      "successAt": "2024-09-10T16:08:46.038Z"
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "error": "\"id\" was not found"
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          }
        }
      }
    }
  }
}
